# Railway Config File for shk2t-t3ban
# Reference: https://docs.railway.app/reference/config-as-code

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node ./src/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/app/v1/users/user"
healthcheckTimeout = 30

[env]
PORT = "3000"
NODE_ENV = "production"
JWT_EXPIRES_IN = "30"
DEFAULT_ORGANIZATION_ID = "website-org"
DATABASE_Atlas = "mongodb+srv://nzmfix4_db_user:JKLC5MK3Qlol8UFY@bishoy-cluster.bb2crte.mongodb.net/?appName=Bishoy-cluster"
JWT_SECRET = "a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6!@#"
RAILWAY_PUBLIC_DOMAIN = "shk2t-t3ban-production.up.railway.app"
RAILWAY_PRIVATE_DOMAIN = "shk2t-t3ban.railway.internal"
RAILWAY_PROJECT_NAME = "luminous-kindness"
RAILWAY_ENVIRONMENT_NAME = "production"
RAILWAY_SERVICE_NAME = "shk2t-t3ban"
